// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALZUND-5Oz4WzL0a6kJ5soFVRRv5-PfKE',
    appId: '1:750604423766:web:cbf4e18ddfdd6b8346e1f7',
    messagingSenderId: '750604423766',
    projectId: 'my-first-firebase-projec-65313',
    authDomain: 'my-first-firebase-projec-65313.firebaseapp.com',
    databaseURL: 'https://my-first-firebase-projec-65313-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-firebase-projec-65313.appspot.com',
    measurementId: 'G-PXBDWYY56Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlzbwETkxPCHJzjZ7f6PHe7XSW9fNetrI',
    appId: '1:750604423766:android:272242d0cd57b98746e1f7',
    messagingSenderId: '750604423766',
    projectId: 'my-first-firebase-projec-65313',
    databaseURL: 'https://my-first-firebase-projec-65313-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-firebase-projec-65313.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY-9uTuy1_s7VQtYqg3m1neiEKqBUo9BU',
    appId: '1:750604423766:ios:e3b8fbbf3d32c60046e1f7',
    messagingSenderId: '750604423766',
    projectId: 'my-first-firebase-projec-65313',
    databaseURL: 'https://my-first-firebase-projec-65313-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-firebase-projec-65313.appspot.com',
    iosBundleId: 'com.example.lab11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY-9uTuy1_s7VQtYqg3m1neiEKqBUo9BU',
    appId: '1:750604423766:ios:406dc06957b12d1b46e1f7',
    messagingSenderId: '750604423766',
    projectId: 'my-first-firebase-projec-65313',
    databaseURL: 'https://my-first-firebase-projec-65313-default-rtdb.firebaseio.com',
    storageBucket: 'my-first-firebase-projec-65313.appspot.com',
    iosBundleId: 'com.example.lab11.RunnerTests',
  );
}
